### ISSUE TITLE
Show saved gradients in gradient inspector

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#118]
Just like for swatches, we should show shared gradients within the picker popup:

<img width="227" alt="Screen_Shot_2021-06-17_at_8_03_42_AM" src="https://user-images.githubusercontent.com/1198882/122423614-e2839f00-cf42-11eb-9373-79fd50cd7cab.png">

^ This is a screenshot from Sketch, but our version should look just like our swatches list/grid

To add a new gradient, we can use a button:

<img width="242" alt="Screenshot_6_17_21__8_08_AM" src="https://user-images.githubusercontent.com/1198882/122423992-37271a00-cf43-11eb-8178-e842d4f37c4f.png">

Are gradients detachable? We can investigate and decide if we need to support that, I'm not sure how shared gradients work (are they shared by ID?).

**Comment by milg15** [comment]
There doesn't seem to be any id connecting them 🤔 I'll look a bit more into it but I don't see anything obvious in the file on how they are connected.
