### ISSUE TITLE
Add "delete layer" button

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#15]
Add a button to the toolbar for deleting any selected layer(s)

Details:
- There should be a corresponding `deleteLayer` action, that takes a layer id, or an array of layer ids, and deletes them from the layer hierarchy
- This can use the `TrashIcon` component for the icon

**Comment by milg15** [comment]
Could it also be when pressing the del key?

**Comment by dabbott** [comment]
We definitely need keyboard shortcuts everywhere, but it's going to be a big task, so I've been putting it off 😂

**Comment by milg15** [comment]
This branch was created from the other branch I was working on 😅  So it has more changes than it should. I'll be moving the branch to be in sync with main instead. I'll just delete the other one and create a new one.
