### ISSUE TITLE
Updating a theme style should update all layers using that style

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#19]
## Feature

When the user changes a theme style, we want to update all layers using that style to have the new properties.

For example, suppose the user changes the fill color of this "Success" style:

![Screen Shot 2021-04-11 at 12 57 28 PM](https://user-images.githubusercontent.com/1198882/114319235-7e1d0d00-9ac5-11eb-93d3-00b2b9d786bd.png)

We should find any layer using the "Success" style and replace the layer's entire style with the updated "Success" style.

Similarly, if the user deletes the "Success" style, we should detach that style from any layers using it.

## Implementation

We should do this as part of any action where we support modifying theme styles. I think right now that's `"updateThemeStyle"` and `"setThemeStyle"` (to handle deletions).

I'm thinking the algorithm to update layers looks like this:

- For each page in our document (`state.sketch.pages`):
  - Use `Layers.findAllIndexPaths` to find all layers using the `sharedStyleId` of e.g. the "Success" style
  - Iterate over each layer using `accessPageLayers`
  - Replace the existing `layer.style` with the `sharedStyleId` (assigning a new `uuid()` like we do elsewhere)

And when a theme style is deleted:

- For each page in our document (`state.sketch.pages`):
  - Use `Layers.findAllIndexPaths` to find all layers using the `sharedStyleId` of e.g. the "Success" style
  - Iterate over each layer using `accessPageLayers`
  - Delete the `sharedStyleId`

**Comment by milg15** [comment]
I am able to do the delete but not the update layers. Since the changes on the themeStyles are done by different actions (border, fill, opacity and shadow). How could I handle them all? 🤔 

Oh! Also how can I get all the pages? I noticed that it's only using the current page with this code. 
`const pageIndex = getCurrentPageIndex(state);`

**Comment by dabbott** [comment]
That's a good point. Since all the actions are handled in one place, can we do the updating here? https://github.com/noya-app/noya/blob/eb3263b514801ccbd26abbb31ae50008615e1691/packages/noya-state/src/reducers/application.ts#L500

We can use `state.sketch.pages` to get all the pages. I don't think we need a function for that since it's pretty short

**Comment by milg15** [comment]
oh right! They are all bundled in one case, I forgot for a bit! Okey I think it can work there 👍

**Comment by milg15** [comment]
Solved by #21
