### ISSUE TITLE
Improve working with multiple pages

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#23]
## Feature

Users should be able to add, delete, duplicate and rename pages.

![Screen Shot 2021-04-14 at 3 19 42 PM](https://user-images.githubusercontent.com/1198882/114787611-f2111c80-9d34-11eb-9b80-8504a31dda1d.png)

The actions we should support:
- `addPage` - When the user clicks the "+" button in the UI, we should `prompt()` them to choose a name, and then add a blank page with that name to the list of pages
- `renamePage` - This should `prompt()` the user to choose a new name for the selected page
- `deletePage` - Delete the selected page from the list of pages
- `duplicatePage` - This should make a copy of the selected page. **We'll need to change the `do_objectID` of the page, and every layer and style** in the page. Anything with a `do_objectID` needs a new `uuid()`. When a page is duplicated, the name of the copy should be `${originalPageName} Copy`

### Suggestions

- I've already added the context menu UI, so this is mostly about writing the actions. It's OK to change existing code to make this work
- For adding a new page, we might want a JSON file like we did for styles? Or maybe there's a better way
- We have 2 actions that work with the list of pages, `selectPage` and `movePage`, which might be useful to look at

**Comment by milg15** [comment]
I have a question, about deleting. I am guessing when I delete one layer I should auto select another one but in the case I don't have any page what should I show?

**Comment by dabbott** [comment]
Good question! What sketch does is: the last page can't be deleted, so they don't even show "Delete" in the menu if there's only 1 page:

![Screen Shot 2021-04-14 at 7 09 20 PM](https://user-images.githubusercontent.com/1198882/114803771-f0efe780-9d54-11eb-82a1-7c4bbbf6613f.png)

**Comment by milg15** [comment]
Oh awesome! I'll add that condition 😄

**Comment by dabbott** [comment]
You can also do:

```tsx
[
  { value: 'duplicate', title: 'Duplicate Page' },
  { value: 'rename', title: 'Rename Page' },
  ...moreThanOnePage ? [{ value: 'delete', title: 'Delete Page' }] : [],
]
```

**Comment by milg15** [comment]
> You can also do:
> 
> ```tsx
> [
>   { value: 'duplicate', title: 'Duplicate Page' },
>   { value: 'rename', title: 'Rename Page' },
>   ...moreThanOnePage ? [{ value: 'delete', title: 'Delete Page' }] : [],
> ]
> ```

I did it like this but I have an error where the typescript isn't pickiup the 'delete' as a MenuItemType. I had to explicity add the type, I'll leave it like this and do a PR for now but maybe there is a solution.

```
...(moreThanOnePage
        ? [{ value: 'delete' as MenuItemType, title: 'Delete Page' }]
        : []),
```

**Comment by dabbott** [comment]
Ah, that makes sense. What you have is a good solution.
