### ISSUE TITLE
Add context menu to grid items

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#24]
## Feature

Let's add a right-click context menu to items in the grid on the theme tab.

![Screen Shot 2021-04-14 at 3 53 57 PM](https://user-images.githubusercontent.com/1198882/114791071-abbebc00-9d3a-11eb-94a3-0ad0579ebbce.png)

To keep this issue small, let's just implement `Delete` in the menu, for now. We can add the other menu items in another issue.

## Implementation

We should use `ContextMenu` from the `noya-designsystem` package. It can be rendered similar to:

```tsx
<ContextMenu.Root<MenuItemType>
  items={menuItems}
  onSelect={onSelectMenuItem}
>
  {/* render a the content of the grid item here */}
</ContextMenu.Root>
```

**Important**: `ContextMenu` should go in `GridView.tsx`, **not** in SwatchesGrid, LayerStylesGrid, etc

We will need to wrap `GridItem` in `forwardRef` to get this to work. You can hopefully refer to `ListView.Row` for a lot of this (and it should be a bit simpler, since we don't need to support sorting).

Each `GridItem` should take these 3 props, just like `ListView.Row`:

https://github.com/noya-app/noya/blob/7ec3094af2092516600c2eab7a660a0dafd3048a/packages/noya-designsystem/src/components/ListView.tsx#L153-L155

**Comment by milg15** [comment]
I think I could implement more actions in this issue.

I am not really sure where to use the `ref` it gives me an error when I add it. The action works correcty I believe (The copy was me trying to see if I could add more)
![image](https://user-images.githubusercontent.com/16924758/114797116-12060780-9d58-11eb-808e-c2ae43c4c107.png)

**Comment by dabbott** [comment]
If you want you could add `duplicate` and `rename` in this issue. After we get this one in, I'm going to make a new one about grouping, so we'll come back to that next. Generally I prefer smaller PRs though, cause they're more focused, and they're also less likely to cause merge conflicts.

The ref should probably be passed to `SwatchContainer` (in the current code), but if it's working I can take a look at what you have first
