### ISSUE TITLE
Add grouping on themes tab

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#28]
## Feature

Theme components (swatches, styles, etc) should support grouping. Groups are determined by the _name_ of the swatch/style. Any slash `"/"` in the name indicates a group.

So for example, suppose we have the following swatch names:

```
"A"
"My Group/B"
"My Group/Nested Group 1/C"
"My Group/Nested Group 1/D"
"My Group/Nested Group 2/E"
```

Any swatches without a slash, like "A", are displayed at the top of the grid view. Every other swatch will be displayed in a separate group with a section title.

In Sketch it would look like this:

![Screen Shot 2021-04-15 at 9 01 13 AM](https://user-images.githubusercontent.com/1198882/114900894-259d8680-9dc9-11eb-9899-496f48f04761.png)

In terms of React components, I'd think of it as:

```tsx
<GridView.Root>
  <GridView.Section>
    <GridView.Item title="A" ... />
  </GridView.Section>
  <GridView.SectionHeader title="My Group" />
  <GridView.Section>
    <GridView.Item title="B" ... />
  </GridView.Section>
  <GridView.SectionHeader title="My Group / Nested Group 1" />
  <GridView.Section>
    <GridView.Item title="C" ... />
    <GridView.Item title="D" ... />
  </GridView.Section>
  <GridView.SectionHeader title="My Group / Nested Group 2" />
  <GridView.Section>
    <GridView.Item title="E" ... />
  </GridView.Section>
<GridView.Root>
```

On the left sidebar we should display a `TreeView` containing all groups. Clicking a row in the tree should filter the grid to show just a single section. By default, "All Color Variables" should be selected, which does not filter the grid. 

![Screen Shot 2021-04-15 at 9 02 45 AM](https://user-images.githubusercontent.com/1198882/114901135-5b426f80-9dc9-11eb-85a4-995d30fbeca7.png)

To make a new group, we can select swatches and choose "Group" from the context menu:

![Screen Shot 2021-04-15 at 9 13 39 AM](https://user-images.githubusercontent.com/1198882/114902650-e112ea80-9dca-11eb-8b16-eb8514a43800.png)

This should `prompt()` the user for a group name, which we then add to the name of each swatch. So if the user enters "Test", then we'd change the names of swatches "C" and "D" to be "Test/C" and "Test/D".

The `NameInspector` for a swatch in a group should NOT show the group name. So even though the full name of this swatch is "My Group/Nested Group 1/C", we will just show the last part of the name, "C":

![Screen Shot 2021-04-15 at 9 23 07 AM](https://user-images.githubusercontent.com/1198882/114903973-34d20380-9dcc-11eb-8c59-ee30f2675334.png)

Swatches can be ungrouped using "Ungroup" in the context menu on the tree, which in this case will delete the "Nested Group 1/" portion of the name:

![Screen Shot 2021-04-15 at 9 27 46 AM](https://user-images.githubusercontent.com/1198882/114904595-e113ea00-9dcc-11eb-9c7e-b779ee53b4c4.png)

## Suggestions

- I'd suggest adding a `GridView.Section` and `GridView.SectionHeader` to support this UI
- Swatches are stored in a single array, but we want to display them in groups based on their names. We might want to first write a function that converts the array into a tree-like data type, where we group/sort the swatches based on name. Then we can flatten that tree before rendering, similar to https://github.com/noya-app/noya/blob/main/packages/app/src/containers/LayerList.tsx#L33-L43
- We don't need to handle expand/collapse in the tree
- The only context menu items we need to add as part of this issue are: "Group" when right-clicking a swatch, and "Ungroup" when right-clicking a group in the tree
- If it's easier, we can start with just swatches, and figure out how to make the code more general from there to support styles, etc

**Comment by milg15** [comment]
This is how the look grouped for now
![image](https://user-images.githubusercontent.com/16924758/114917088-319a4000-9deb-11eb-9f25-ab5945f4d0fc.png)

**Comment by milg15** [comment]
How will it handle creating nested groups? Just adding **/** for now?

**Comment by dabbott** [comment]
> How will it handle creating nested groups?

The context menu item "Group" should create both groups and nested groups. And groups can be nested arbitrarily deep, e.g. "A/B/C/D/E/F" is a valid nested group.

When the user clicks "Group" in the context menu, any selected swatches should be put in a nested group within that group. If there are swatches selected that are in different groups, they should all be moved to the group of the last swatch.  Some examples:

If just "A" is selected and the user clicks "Group", then we convert it to "Group/A" 
If just "A/B/C" is selected and the user clicks "Group", then we convert it to "A/B/Group/C"
If both "X" and "A/B/C" are selected and the user clicks "Group", we convert them to "A/B/Group/X" and "A/B/Group/C" at the same time

We can use `prompt()` to ask for a group name, for now

> it's tricky with nested names and groups

One thing that might make it simpler is using `onSubmit` instead of `onChange` on the inputs, since this waits for the user to press enter or click outside the input field before updating groups (this is Sketch's behavior)

![Screen Shot 2021-04-15 at 2 27 57 PM](https://user-images.githubusercontent.com/1198882/114940514-c8b8c500-9df6-11eb-8458-c8b51e219b86.png)
