### ISSUE TITLE
Dragging a layer when zoomed in should still snap to pixels

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#285]

**Comment by dabbott** [comment]
@milg15 I'm not totally sure what's involved with this, but do you want to investigate and try it?

**Comment by milg15** [comment]
> @milg15 I'm not totally sure what's involved with this, but do you want to investigate and try it?

Yes! Do you have an example for this?

**Comment by milg15** [comment]
Ohh I understand. I think I have an idea on how to solve this

**Comment by dabbott** [comment]
Here's an example. If I draw a rectangle when zoom is greater than 100%, the x/y/w/h should all still be integers. Right now the dimensions are decimals:

https://user-images.githubusercontent.com/1198882/143488260-db5a4c23-c88e-4d3a-a30a-7e1734237853.mov

We should snap to integer values when:
- drawing a layer
- moving/dragging a layer
- scaling a layer

**Comment by milg15** [comment]
I think just Rounding the numbers works.
