### ISSUE TITLE
When pasting a layer, it should be placed at the same location as the original if visible

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#287]
When pasting a layer:

- If the original layer it was copied from is visible on screen, then the pasted layer should go in the same position
- If the original layer isn't visible or isn't in the document at all, then:
  - if a group is selected, the pasted layer should go in the center of the group
  - if an individual layer is selected, 
    - if the parent of the selected layer isn't the page, the pasted layer should go in the center of that parent
  - otherwise, the pasted layer should go in the center of the page 

I believe this is Figma's pasting behavior

**Comment by milg15** [comment]
I'll change this behavior and change the test based on that I'll change the test #286
