### ISSUE TITLE
Add grouping support for layer styles

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#32]
We should support all the same grouping features for layer styles. This includes showing a TreeView in the left sidebar for layer styles.

I think it's fine if we mostly duplicate the code between these. If you see any good opportunities for creating shared utils, that could be useful too though, before we add text styles and symbols.

> This relies on https://github.com/noya-app/noya/pull/30, so take a look at that PR first and I'll merge it before starting this

**Comment by milg15** [comment]
I change the files with stylelayer to themelayer, since that's the name we are using in all the actions 😅
