### ISSUE TITLE
Changing a theme color should update all layers/styles

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#33]
## UX

Currently when a theme color changes, layer styles and theme styles using that color should also update. 

For example, suppose we have a theme color "Primary" that's blue.

| | Theme | Canvas |
| --- | --- | --- |
| Before | ![Screen Shot 2021-04-18 at 4 44 10 PM](https://user-images.githubusercontent.com/1198882/115166016-daec6a80-a065-11eb-8cdf-e102b8aa9779.png) | ![Screen Shot 2021-04-18 at 4 44 48 PM](https://user-images.githubusercontent.com/1198882/115166018-dfb11e80-a065-11eb-90df-43b75974d88a.png) |

When I change "Primary" to green, currently the layer stays blue:

| | Theme | Canvas |
| --- | --- | --- |
| Current behavior | ![Screen Shot 2021-04-18 at 4 48 54 PM](https://user-images.githubusercontent.com/1198882/115166040-f9526600-a065-11eb-98f4-4a6cb4a7e2d4.png) | ![Screen Shot 2021-04-18 at 4 45 06 PM](https://user-images.githubusercontent.com/1198882/115166048-01aaa100-a066-11eb-83eb-cc6d70d6e9cc.png) |

We want the layer to turn green also:

| | Theme | Canvas |
| --- | --- | --- |
| Desired behavior | ![Screen Shot 2021-04-18 at 4 48 54 PM](https://user-images.githubusercontent.com/1198882/115166040-f9526600-a065-11eb-98f4-4a6cb4a7e2d4.png) | ![Screen Shot 2021-04-18 at 5 00 13 PM](https://user-images.githubusercontent.com/1198882/115166356-98c42880-a067-11eb-8964-b6679eea2242.png) |

## Implementation

We know which colors are linked to theme styles based on `swatchID`. However, we don't currently have a way to visit/traverse every color object.

I would start by making a function that visits each color object, which will make it easier to keep that logic separate. We'll probably have other use cases for visiting each color in the future (e.g. to show a section containing "colors used in this document").

For example:

```ts
// Run a function `f` for each color object used in the file.
// This includes every fill, border, and shadow in every layer style and shared style.
// This does not visit theme colors in the `sharedSwatches` object.
function visitColors(sketch: SketchFile, f: (Sketch.Color: color) => void) {}
```

Once we have this, we can call it to set each color to a new value if it matches a specific `swatchID`.

If it's easier, you could first make a `visitStyles` function that visits every layer style and shared style, and build `visitColors` on top of that.

**Comment by milg15** [comment]
Wouldn't this function be very very costly ? 😅  Since it will have to run in the produce function
