### ISSUE TITLE
Copy paste within a box bug

### ISSUE THREAD

**Issue by williambarberjr** [noya-app/noya#369]
When attempting to copy paste highlighted text from within one box to another, the entire box object itself is also copied and pasted.

Use case through which I found this bug:
Step 1 - I drew in 5 boxes of decreasing width to get a funnel like view for showing sales funnel stats in a dashboard.
Step 2 - decided I liked the idea and wanted to style each box to make them look nicer (shadow, rounded corners etc)
Step 3 - I get one box looking the way I want, highlight the list of hashtags I decided on for styling, press control + c on my keyboard.
[Bug] Step 4 - when click into the next box and press control + v to paste, I can see that I had copied not just the selected text, but also box itself such that I've now pasted both the style changes I wanted AND a new copy of the box I only wanted to copy text from.

**Comment by dabbott** [comment]
Aha, you're right! I can reproduce this. Thanks for reporting, I'll fix this soon.

**Comment by dabbott** [comment]
Should be fixed! If you run into it again let me know.
