### ISSUE TITLE
Add "Duplicate" to theme context menu

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#37]
We should support duplicating theme components via the context menu:

![Screen Shot 2021-04-18 at 6 58 28 PM](https://user-images.githubusercontent.com/1198882/115171537-12641280-a078-11eb-8d96-6dfc7325d16f.png)

For naming, we should add a `" 2"`. If the name already ends in a space followed by a number, we should increment that number. So for example, if I duplicate:

```
Test    => Test 2
Test 2  => Test 3
Test 12 => Test 13
Test2   => Test2 2
```

I'd recommend writing a separate util function that takes in a name and returns the new name. I would probably implement this with a regular expression, but that's up to you. Something like:

```ts
const numberSuffixRegExp = /(.*?)( \d+)?$/
  
function getIncrementedName(name: string): string {
  const [, prefix, number] = name.match(numberSuffixRegExp)
  // ...
}
```

We'll have other uses for this function in the future, so I'd put it in `noya-utils` and add tests for the cases I listed above.

**Comment by milg15** [comment]
Oh I just noticed an issue 🤔 Usually when you duplicate somthing and you do it again. The next one has the next value. Example if I click duplicate on Test the next name will be Test 2 and if I duplicate Test again it should be Test 3, right???

**Comment by dabbott** [comment]
That's a great point! How do you think we should handle that?
