### ISSUE TITLE
Text style inspector

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#43]
## Feature

Implement the UI for the text style inspector. This will be used for both text layers and theme text styles. 

In this issue we'll focus on just the React components/layout for the inspector and **use hardcoded/fake data** for the input elements - afterward I'll make a follow-up issue to populate the input elements with real data and support changing it via actions.

Elements we should have:
- Font family, e.g. Helvetica, Arial (we don't need the fancy search, use our design system `Select`)
- Font face, e.g. Regular, Bold (`Select`)
- Font size (`NumberInput`)
- Letter spacing, called "Character" in the example video (`NumberInput`)
- Line spacing, "Line" (`NumberInput`)
- Paragraph spacing, "Paragraph" (`NumberInput`)
- Color (`ColorInputFieldWithPicker`)
- Alignment (`RadioGroup`)
- Horizontal text alignment (`RadioGroup`)
- Vertical text alignment (`RadioGroup`)
- Text decoration (`Select`)
- Text transform (`RadioGroup`)

We don't need to support the expand/collapse by clicking the gear. We can always show the "Text Options" section

https://user-images.githubusercontent.com/1198882/115790625-dc76a500-a37b-11eb-85c1-979e99c44afa.mov

**Comment by milg15** [comment]
Oh! This one is interesting 😮 !
