### ISSUE TITLE
Support modifying text styles

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#45]
## Feature

We should allow displaying and modifying the styles of text layers. This means populating the input fields in the `TextStyleInspector` and creating actions to modify the values in the `state.sketch` file data. We can use `TextLayers.sketch` to test the various style properties.

For reference, this is how `TextLayers.sketch` looks currently:

| App | Screenshot |
| --- | --- |
| Sketch | ![Screen Shot 2021-04-23 at 3 11 00 PM](https://user-images.githubusercontent.com/1198882/115935469-1614e200-a448-11eb-867b-25c668621b17.png) |
| Noya | <img width="1792" alt="Screen Shot 2021-04-23 at 3 11 29 PM" src="https://user-images.githubusercontent.com/1198882/115935509-2cbb3900-a448-11eb-9762-b6a820c9ffbd.png"> |

## Step 1

First, I want to document how the JSON looks for these text styles. Some of it we can figure out from the TypeScript definitions for the Sketch file format, but some of it isn't documented there. I'd like to have a short description/example of where each style property is stored (we can write it in this GitHub issue).

## Step 2

Once we've documented how things work, we can implement it.

## Not part of this issue

- Modifying the actual text/string of the layer (and not just the style) will be complex and will come later.
- Sometimes the layout of the text will be a tiny bit off. E.g. one character might wrap when it's not supposed to. That's OK for now
![Screen Shot 2021-04-23 at 3 21 21 PM](https://user-images.githubusercontent.com/1198882/115935222-9129c880-a447-11eb-8ddd-a46d9790ff5d.png)
- Some properties might be hard to implement at the moment. For example, font family will require loading font files from... somewhere. Anything difficult we can leave for another time

**Comment by milg15** [comment]
"font family will require loading font files from... somewhere" 😆 I understand

**Comment by milg15** [comment]
I am working with two types the `attributedString` and the `TextStyle` what I notice it's that `TextStyle` it's a "global" style for the text and I think the `attributedString` allows to have multiple styles in the same `TextLayer` from different sections of the text.
Here it's the attributedString type.

```typescript
export declare type StringAttribute = {
    _class: 'stringAttribute';
    location: number;
    length: number;
    attributes: {
        kerning?: number;
        textStyleVerticalAlignmentKey?: TextVerticalAlignment;
        MSAttributedStringFontAttribute: FontDescriptor;
        MSAttributedStringColorAttribute?: Color;
        paragraphStyle?: ParagraphStyle;
    };
};
```

**Comment by dabbott** [comment]
I'd like to see more detail on a few of the properties:

- How is the font face stored? Is "Regular" stored somewhere, or is that the default? What does it look like when a font is both "Bold" and "Oblique"?
- How is "auto" letter spacing stored? Is `kerning` undefined in that case?
- Same for line spacing, is there a default? Or does it always have a value?

**Comment by milg15** [comment]
1. The font face it's stored here `MSAttributedStringFontAttribute`
```typescript
export declare type FontDescriptor = {
    _class: 'fontDescriptor';
    attributes: {
        name: string;
        size: number;
        variation?: {
            [key: string]: number | number;
        };
    };
};
```

The name of the fonts face are stored inside the name with the fontfamily followed by a dash. like this
* Arial         (regular)
* Arial-Bold
* Arial-BoldOblique

2. When it's auto kerning it's undefined and when it's 0 it shows a 0.
3. The line spacing it's handle here
```typescript 
export declare type ParagraphStyle = {
    _class: 'paragraphStyle';
    alignment?: TextHorizontalAlignment;
    maximumLineHeight?: number;
    minimumLineHeight?: number;
    paragraphSpacing?: number;
    allowsDefaultTighteningForTruncation?: number;
};
```
It shows in the `maximumLineHeight` and the `minimumLineHeight` with the same value but when it's the default it doesn't show anything in those values.

Here I saved the types so I can easily find them
https://www.notion.so/mariaisabel/Text-Style-types-4e4d7c1abc314d18b0025d4cc5925193

**Comment by milg15** [comment]
And for what I noticed the textStyle in the style property has the same value of the first attribute in `attributedString`. Even when you have multiple attributes in the text.

**Comment by dabbott** [comment]
Awesome, this is great info! 😁
