### ISSUE TITLE
Support working with theme text styles from the canvas tab

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#56]
We should support applying, creating, updating, detaching, renaming, resetting the styles on text layers.

![Screen Shot 2021-05-10 at 3 46 04 PM](https://user-images.githubusercontent.com/1198882/117733683-d6b7f680-b1a6-11eb-8b54-cc4fbdcfb0ec.png)

This is essentially the same as https://github.com/noya-app/noya/issues/13, only for text layer styles specifically, rather than layer styles.

**Comment by milg15** [comment]
In the case we selected a text and a layer style ? Which one should I show ?

**Comment by dabbott** [comment]
In that case, Sketch shows neither. So there's no theme style/text style section at all. Let's go with that behavior
