### ISSUE TITLE
Symbols

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#60]
# Symbols

Symbols are re-usable groups of layers, i.e. UI components. Symbols support:

- Overrides - specific properties on individual layers can be overridden
- "Smart layout" - the position and size of layers will update automatically as the symbol instance scales or properties are overridden
- Libraries - symbols can be imported from an external `.sketch` file by linking that file as a library

Symbols are a big feature, and we won't support them all at once. For now, let's ignore "smart layout" and libraries, and focus on 3 things:

- Symbol rendering (on the canvas)
- Symbol instance inspector (overrides)
- Symbol browser (in the themes tab)

## Symbol rendering

We'll need to add a new case to `SketchLayer` that renders `symbolInstance` and `symbolMaster` types.

A symbol has a "master" copy which defines the layer groups and default values (e.g. string value of a text layer) of the symbol. Then, it can be instantiated multiple times, and each instance can potentially override the default values.

https://github.com/noya-app/noya/blob/4cdb07196bd4c59992ddb21d5db7c13fb2e3a280/packages/noya-renderer/src/components/layers/SketchLayer.tsx#L19-L39

## Symbol instance inspector

![Screen Shot 2021-05-12 at 11 21 44 AM](https://user-images.githubusercontent.com/1198882/118025035-3d0e5780-b314-11eb-9012-5ba02b4a15c7.png)

Symbol instances show an inspector with 2 new sections we should support:

- A "SYMBOL" section
  - allows detaching the symbol instance from the symbol master, cloning all layers within the symbol and placing them in the page as regular layers
  - supports choosing a different symbol from a dropdown
  - "edit", which focuses & selects the symbol master in the canvas (i.e. it changes the selected layer id to the symbol master's layer id, and changes the selected page to the page containing the symbol master)

- An "Overrides" section which allows replacing certain properties of layers that are defined as overridable.

## Symbol browser

![Screen Shot 2021-05-12 at 11 20 02 AM](https://user-images.githubusercontent.com/1198882/118024851-020c2400-b314-11eb-9079-337ac4c7ea86.png)

On the themes tab, we should show a preview of each symbol master. Symbols support grouping via `"/"` just like other theme components. In our initial implementation, we should only support the "NAME" field of the inspector, and ignore everything else.

---

I'll break this down into smaller issues, which I'll list here.

**Comment by milg15** [comment]
- The symbols inspector tab shouldn't show all the style options (remove fill and borders) add tint.
- Text and Images can be overridden. 
- Add Symbols section into inspector (detach, reset, go to symbol, edit name)
- Sketch has a Overrides section in the inspector.

**Comment by milg15** [comment]
I think the only thing missing for this issue to be complete it's adding the Tint in the inspectors, right?

**Comment by milg15** [comment]
I think the only thing missing for this issue to be complete it's adding the Tint in the inspectors, right?

**Comment by dabbott** [comment]
We definitely need to handle inserting a Symbol, but let's wait till Leanne's smart snap PR is merged, cause that's gonna overlap the files a lot.

Tint would be good. It should be almost exactly the same code as fill color, I think. The only difference is, there's at most 1 tint in the array:

<img width="350" alt="Screen Shot 2021-05-29 at 10 57 31 AM" src="https://user-images.githubusercontent.com/1198882/120080208-ac05e300-c06c-11eb-8f2b-42e28c5fccf4.png">
