### ISSUE TITLE
Symbol browser in themes tab

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#71]
This issue is a prerequisite for Symbols: #60

### Symbol browser

On the themes tab, we should show a preview of each symbol master. Symbols support grouping via `"/"` just like other theme components.

We should show symbols from any page, not just the "Symbols" page. I.e. to find all the symbols in a document, we should search each page for SymbolMaster layers.

![Screen Shot 2021-05-12 at 11 20 02 AM](https://user-images.githubusercontent.com/1198882/118024851-020c2400-b314-11eb-9079-337ac4c7ea86.png)

### Inspector

In our initial implementation, we should only support the "Name" field of the inspector, and ignore the other buttons and sections.

![Pasted_Image_5_18_21__9_24_AM](https://user-images.githubusercontent.com/1198882/118688499-f65ca980-b7ba-11eb-8573-84aa8fe336f3.png)

**Comment by milg15** [comment]
Oh! Okey without the inspector it's simpler! I'll get to it 👍
