### ISSUE TITLE
Add color swatches to color picker

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#8]
## Feature

When picking a color for borders, fills, and shadows, we should show the document's color swatches in the color picker popup.

## Possible implementation

- The main file here is `ColorInputFieldWithPicker.tsx`. 
- We should show the document's `sharedSwatches` and allow choosing one to set the color
  - The `Sketch.Color` type has an optional `swatchID` field - we can use this field to determine if we should show an item as selected in the grid/list. This also means we should set the `swatchID` when the user picks a color swatch.
- We should support 2 layouts: a grid and a list. We may want to make a separate file for each of these components.
  - For the **list** layout, we should use our `ListView` component. It's OK if it the spacing looks weird - I can fix that later - let's just focus on functionality for now
  - I think the **grid** layout can be a new component (probably using CSS grid again). It's pretty different from our `GridView`, so I don't think we need to reuse that.
- We shouldn't need to handle scrolling specially - the whole popup should scroll if the list gets long, and I think this already works correctly.
- Ignore the `"Document colors"` dropdown for now, since we don't have any other kinds of colors yet

## UX

Here's a mockup of the two views:

| Grid | List |
| --- | --- |
| ![swatch-grid](https://user-images.githubusercontent.com/1198882/111700577-d169ab80-87f6-11eb-992c-ac16550e8050.png) | ![swatch-list](https://user-images.githubusercontent.com/1198882/111700555-cadb3400-87f6-11eb-965c-7a346e3544e6.png) |

> Note that these aren't totally accurate, since they show a selected swatch, but the color picker itself shows a different color. The color picker on the left should be orange and the color picker on the right should be red, but instead they're both blue

**Comment by milg15** [comment]
Should I show all the colors? or limit it to a few in the grid view? in case there were a lot

**Comment by dabbott** [comment]
Let's show all of them. I added an `overflowY: auto` to the popup already so it should look reasonable. Maybe in the future we can add a more sophisticated version, like with search.

**Comment by milg15** [comment]
Do I create a new branch for this? Or do I keep it in the color-swatches branch?
