### ISSUE TITLE
SymbolMaster inspector

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#81]
We should show the SymbolMaster inspector when we click a symbolMaster layer on the canvas _or_ when we select a symbol on the themes tab. The inspector has the following sections:

### Section: Symbol Source

This configures properties of the SymbolMaster. We should only show the 2 bottom checkboxes when the "Background Color" checkbox is checked.

![Artboard](https://user-images.githubusercontent.com/1198882/119203892-feca1400-ba48-11eb-8866-4ebb981e57b6.png)

I think this uses the following `SymbolMaster` properties:

```ts
resizesContent: boolean
backgroundColor: Color;
hasBackgroundColor: boolean;
includeBackgroundColorInInstance: boolean;
includeBackgroundColorInExport: boolean;
```

### Section: Layout

This section controls automatic layouts (the `groupLayout` property). Here are the possible options:

![Artboard Copy](https://user-images.githubusercontent.com/1198882/119204217-c2e37e80-ba49-11eb-9689-8de7579af435.png)

When "None" is selected, we should hide the "Minimum width" and disable the bottom radio group.

I think "None" uses the type `FreeformGroupLayout` while the other options use `InferredGroupLayout`.

### Section: Manage Overrides

All symbols with _at least one overridable property_ should show an "Allow Overrides" (`allowsOverrides`) checkbox. We find these properties by iterating over `overrideProperties`.

![Artboard Copy 2](https://user-images.githubusercontent.com/1198882/119204795-4c478080-ba4b-11eb-89ab-f0416105be3b.png)

How overrides work: Layers within a SymbolMaster can have one or more overrides, depending on the type of layer and the layer's properties. The 5 kinds of possible overrides are: text, style, text style, image, and symbol instance. But most layers will only have one or two. We also show the overrides from any nested SymbolInstance layers.

To show the layer name, we'll have to use the `overrideProperties` and look up the target layer. See:

https://github.com/noya-app/noya/blob/db0d76701f2f7905b2acb115c934f1340e654a56/packages/noya-renderer/src/components/layers/SketchSymbolInstance.tsx#L51-L59

https://github.com/noya-app/noya/blob/db0d76701f2f7905b2acb115c934f1340e654a56/packages/noya-state/src/overrides.ts

## Screenshot

All together, here's what the inspector looks like for our "Card" symbol:

![Screen Shot 2021-05-21 at 4 00 15 PM](https://user-images.githubusercontent.com/1198882/119205661-b103da80-ba4d-11eb-813b-97ae533658b4.png)

## Implementation

- We don't need to copy the Sketch UI exactly. We should use own components from `noya-designsystem` where possible to make something that looks close.
- We should use our `TreeView` for the overrides list, even though it looks a little different
- We don't need to implement Sketch's section expand/collapse feature
- For simplicity, we should only show these sections if we select exactly one SymbolMaster for now. We can revisit multiple selections another time

**Comment by milg15** [comment]
The current branch doesn't Manage Overrides
