### ISSUE TITLE
Create swatches from color picker

### ISSUE THREAD

**Issue by dabbott** [noya-app/noya#99]
The user should be able to create a new swatch without leaving the color picker. 

If the color they've chosen is _not already a swatch_, we should show a button "Create Theme Color" button. This button will `prompt` them to choose a name for the color, create a new theme color, then swap the current fill color with the newly created theme color.

![Bitmap](https://user-images.githubusercontent.com/1198882/120555103-6a986f00-c3af-11eb-99a9-f1e2d627ca1d.png)

Otherwise, if they've chosen an existing swatch from the list, we should show a button "Detach Theme Color", which will delete the swatchID from the instance of the color they've chosen (i.e. if the user wants to use that color, but doesn't want it to change even if the theme color changes later)

![Group Copy](https://user-images.githubusercontent.com/1198882/120555139-784df480-c3af-11eb-8d81-6ec9ac22af45.png)

(We currently only show hex input and alpha input, which is fine for now)

**Comment by milg15** [comment]
When I have a Theme color connected to a fill, if I change it does it change the Theme Color ??

**Comment by dabbott** [comment]
No, it will just change the fill to a new color with no `swatchID`

**Comment by milg15** [comment]
🤔

**Comment by dabbott** [comment]
No, once you change the fill color it'll be detached, so we would show the "Create Theme Color" button.

Even if the color is a theme color e.g. `#000000`, and the user changes it to something else `#ABCDEF`, and then drags it back to `#000000`, that'll still be detached. We determine if a color is attached to the theme color based on its `swatchID`, so once we delete that, the color is detached.

**Comment by dabbott** [comment]
That's our current behavior, and it's correct already

**Comment by milg15** [comment]
I understand now 😆 I was a bit confused but got it!

**Comment by milg15** [comment]
I am still figuring out the best way to change the SwatchId of the fill since we aren't passing the index of the id to the colorinspector, when I create the swatch I don't have information on which fill I am currently at 🤔

**Comment by dabbott** [comment]
I see what you mean 🤔. I don't think we have a way to set the fill from within the color picker.

I'm thinking we can expose a `onCreateSwatch` and `onDetachSwatch` prop to the `ColorInputFieldWithPicker`. We'll still have to choose the correct action for the different kinds of inspectors, e.g. `setFillColor`, `setBorderColor`, `setShadowColor`, so we probably wouldn't be able to handle this entirely within the color picker anyway
